### ISSUE TITLE
glibconfig.h and gstconfig.h missing

### ISSUE THREAD

**Issue by aferriss** [hiroMTB/vscode_oF#5]
I'm running Ubuntu 16.04 and after installing intellisense was complaining about not being able to find the glibconfig.h and gstconfig.h. I had to move them from elsewhere on my machine. 

`sudo cp /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h /usr/include/glib-2.0/glibconfig.h`

`sudo cp /usr/lib/x86_64-linux-gnu/gstreamer-1.0/include/gst/gstconfig.h /usr/include/gstreamer-1.0/gst/gstconfig.h`

The gstreamer include path in c_cpp_properties.json also needed to be set to  `/usr/include/gstreamer-1.0/gst` in order to be found.

Not sure if this was just my particular setup, but thought I would throw this up in case it helps someone else out!

**Comment by hiroMTB** [comment]
Thanks! 
I still have not managed to setup Linux system on my side.
All Linux feature are done by @anselanza.

Any suggestion @anselanza ?

**Comment by anselanza** [comment]
Yeah, adding paths to included addons header files seems to be a manual process at the moment. Not sure what the best way would be to automate this.

**Comment by hiroMTB** [comment]
glibconfig.h and gstconfig.h are addon related file or should be included as oF core?

Best solution would be generating a project file by ~~project manager~~ ProgectGenerator. It wont be difficult since vscode's project file is relatively simple.

**Comment by anselanza** [comment]
I believe those files are for oF core.

Hmm good idea about Project Generator. I think I'll take a look into that.

**Comment by anselanza** [comment]
Good grief, the Project Generator itself is written in C++. Much as I enjoy using that for openFrameworks projects, it is not the most obvious choice for what is essentially a templating engine, and quite a high barrier for entry to getting a new IDE template set up within that framework. Hmmm.

**Comment by hiroMTB** [comment]
Thanks for checking anselanza!
I re think about it and noticed If we want to support vs code from ProjectGenerator, then it mean vs code must be one of oF official support IDE. oF already has too many IDE support and it must be another pain in future release. Might be nice to keep it as an unofficial IDE only for advanced users?

**Comment by hiroMTB** [comment]
@aferriss
Sorry about off-topic discussion.
Could you send PR if missing glibconfig.h and gstconfig.h must be included in setting files?

**Comment by giuliohome** [comment]
That's ridiculous! It is still open after two years. 

I'm on Fedora, and after searching one by one and adding all the following dirs

            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/linux",
                "/usr/include/gtk-3.0",
                "/usr/include/glib-2.0",
                "/usr/lib64/glib-2.0/include",
                "/usr/include/pango-1.0"
            ],

it keeps complaining

cannot open source file "hb.h" (dependency of "gtk/gtk.h")

and it's unclear how many folders I am supposed to search... it is not manageable...

**Comment by giuliohome** [comment]
It is obvious that it is not manageable, anyway, for your info, this is [the solution ](https://stackoverflow.com/a/62000894/11323942)on my Fedora 31 Linux workstation:

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include/linux",
                "/usr/include/gtk-3.0",
                "/usr/include/glib-2.0",
                "/usr/lib64/glib-2.0/include",
                "/usr/include/pango-1.0",
                "/usr/include/harfbuzz",
                "/usr/include/cairo",
                "/usr/include/gdk-pixbuf-2.0",
                "/usr/include/atk-1.0"
            ],
            "defines": [],
            "compilerPath": "/usr/lib64/ccache/gcc",
            "cStandard": "c11",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by LoneWolfHT** [comment]
Had this issue on Ubuntu 20.04

Adding ```/usr/lib/x86_64-linux-gnu/glib-2.0/include``` to my include path fixes it (Credit to https://stackoverflow.com/a/64360401/11433667)

**Comment by hiroMTB** [comment]
Hello, thanks for reporting this and sorry for your confusion.
Few yeaers ago, I sent a PR which generates vscode project from oF's Project Generator.
It was quickly merged and sine then everyone can use vscode with oF.
and I don't update this repo anymore.

Please check oF main repo and also this thread in the forum.
https://forum.openframeworks.cc/t/vscode-visual-studio-code-of/28504

I close this issue since the vscode setting discussion should move to oF main repo.
But let me know if it is still useful for some reason.

**Comment by lyutian** [comment]
For CentOS8, 
```
# find /usr/ -name glibconfig.h
/usr/lib64/glib-2.0/include/glibconfig.h
```
then, add `/usr/lib64/glib-2.0/include/` into `includePath` of `.vscode/c_cpp_properties.json` file.
