### ISSUE TITLE
unclarity in readme.md

### ISSUE THREAD

**Issue by clankill3r** [hiroMTB/vscode_oF#6]
It says:

`Command + B and select "buid debug" for compiling oF and exampleProject. (excute make command)`

Command + B is the default to hide / show the side bar. I guess you mean `command + shift + b`, however, I can't find a option anywhere to specify it is about a debug build.

**Comment by clankill3r** [comment]
Also step 3 is:

`open project file with vscode(vscode_oF.code-workspace).`

But the file vscode_oF.code-workspace is not included.

**Comment by hiroMTB** [comment]
thanks a lot!
